name: Keep Render Alive

on:
  schedule:
    - cron: "*/10 * * * *"

  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Render Web Service
        run: curl -fsS https://tracking-system-q74x.onrender.com/